---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-backend
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"llama-stack"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy-backend
      app.kubernetes.io/name: canopy-be
  template:
    metadata:
      labels:
        app: canopy-backend
        app.kubernetes.io/name: canopy-be
        monitoring.opendatahub.io/scrape: 'true'
      annotations:
        configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: canopy-be
      containers:
        - name: canopy-backend
          image: quay.io/rhoai-genaiops/canopy-be:0.30
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.MLFLOW_TRACKING_URI }}"
            - name: MLFLOW_TRACKING_INSECURE_TLS
              value: "true"
          volumeMounts:
            - mountPath: /canopy
              name: canopy-config
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: canopy-config.yaml
              path: canopy-config.yaml
            name: canopy-config
          name: canopy-config