---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canopy-backend
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: canopy-backend
