FROM registry.redhat.io/ubi9/python-312@sha256:7a5af0831851a34daf12fd706aed9a5b4f54ef1ae2826a932403b85a9e290c14

COPY . /app/
WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "main.py"]